import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Auto-read Cognito config from amplify_outputs.json (generated by `npx ampx pipeline-deploy` or `npx ampx sandbox`)
const amplifyOutputsPath = resolve(__dirname, '../amplify_outputs.json')
let amplifyOutputs: { auth?: { user_pool_id?: string, user_pool_client_id?: string, aws_region?: string } } | null = null
if (existsSync(amplifyOutputsPath)) {
  try {
    amplifyOutputs = JSON.parse(readFileSync(amplifyOutputsPath, 'utf-8'))
  }
  catch {
    console.warn('[nuxt.config] Failed to parse amplify_outputs.json – Cognito auto-config skipped')
  }
}

const DEFAULT_AWS_REGION = 'eu-central-1'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-01-01',
  future: { compatibilityVersion: 4 },
  devtools: { enabled: true },
  modules: ['@nuxt/ui', '@nuxt/eslint'],

  runtimeConfig: {
    // Private server-side keys (never exposed to browser)
    dynamoTableName: process.env.DYNAMO_TABLE_NAME || 'chatlog-api-keys',
    dynamoAnalysisTableName: process.env.DYNAMO_ANALYSIS_TABLE_NAME || 'chatlog-analysis-requests',
    awsRegion: process.env.AWS_REGION || amplifyOutputs?.auth?.aws_region || DEFAULT_AWS_REGION,
    apiKeyHmacSecret: process.env.API_KEY_HMAC_SECRET || '',

    // Public keys (exposed to browser via useRuntimeConfig().public)
    public: {
      cognitoUserPoolId: amplifyOutputs?.auth?.user_pool_id || '',
      cognitoUserPoolClientId: amplifyOutputs?.auth?.user_pool_client_id || '',
      cognitoRegion: amplifyOutputs?.auth?.aws_region || DEFAULT_AWS_REGION,
    },
  },

  // Transpile AWS Amplify for SSR compatibility
  build: {
    transpile: ['@aws-amplify/ui-vue'],
  },

  // Disable SSR for pages that use browser-only APIs (Amplify Auth)
  ssr: true,

  nitro: {
    // Ensure server-only packages don't leak to client
    externals: {
      inline: ['@aws-sdk/client-dynamodb', '@aws-sdk/lib-dynamodb', '@aws-sdk/client-comprehend'],
    },
  },
})
