import { defineBackend } from '@aws-amplify/backend'
import { apiFunction } from './functions/api/resource.js'
import { auth } from './auth/resource.js'
import {
  AttributeType,
  BillingMode,
  ProjectionType,
  Table,
} from 'aws-cdk-lib/aws-dynamodb'
import { PolicyStatement, Effect } from 'aws-cdk-lib/aws-iam'
import { RemovalPolicy } from 'aws-cdk-lib'
import { Function as LambdaFunction } from 'aws-cdk-lib/aws-lambda'

export const backend = defineBackend({
  auth,
  apiFunction,
})

// ─── DynamoDB tables ──────────────────────────────────────────────────────────
// Table names are auto-generated by CDK (unique per Amplify environment /
// branch), so prod and sandbox always use different tables without any manual
// configuration.  The generated names are written into amplify_outputs.json
// via backend.addOutput() so that the Nuxt app can read them automatically.

const tablesStack = backend.createStack('TablesStack')

/**
 * API Keys table (single-table design)
 *
 * pk  = "USER#<userId>"
 * sk  = "KEY#<keyId>"
 *
 * GSI "KeyHashIndex"
 *   pk  = keyHash   (enables O(1) lookup during X-API-Key validation)
 */
const apiKeysTable = new Table(tablesStack, 'ApiKeysTable', {
  partitionKey: { name: 'pk', type: AttributeType.STRING },
  sortKey: { name: 'sk', type: AttributeType.STRING },
  billingMode: BillingMode.PAY_PER_REQUEST,
  removalPolicy: RemovalPolicy.RETAIN,
})

apiKeysTable.addGlobalSecondaryIndex({
  indexName: 'KeyHashIndex',
  partitionKey: { name: 'keyHash', type: AttributeType.STRING },
  projectionType: ProjectionType.ALL,
})

apiKeysTable.addGlobalSecondaryIndex({
  indexName: 'CheckIdIndex',
  partitionKey: { name: 'checkId', type: AttributeType.STRING },
  projectionType: ProjectionType.ALL,
})

/**
 * Analysis Requests table
 *
 * pk  = "USER#<userId>"
 * sk  = "CALL#<ISO-timestamp>#<callId>"
 *
 * GSI "CallIdIndex"
 *   pk  = callId   (enables O(1) lookup by callId without scanning)
 */
const analysisTable = new Table(tablesStack, 'AnalysisRequestsTable', {
  partitionKey: { name: 'pk', type: AttributeType.STRING },
  sortKey: { name: 'sk', type: AttributeType.STRING },
  billingMode: BillingMode.PAY_PER_REQUEST,
  removalPolicy: RemovalPolicy.RETAIN,
})

analysisTable.addGlobalSecondaryIndex({
  indexName: 'CallIdIndex',
  partitionKey: { name: 'callId', type: AttributeType.STRING },
  projectionType: ProjectionType.ALL,
})

// ─── IAM: grant apiFunction Lambda read/write access to both tables ───────────

const lambdaRole = backend.apiFunction.resources.lambda.role!
apiKeysTable.grantReadWriteData(lambdaRole)
analysisTable.grantReadWriteData(lambdaRole)

// ─── Pass table names as Lambda environment variables ─────────────────────────

const lambdaFunction = backend.apiFunction.resources.lambda as LambdaFunction
lambdaFunction.addEnvironment('DYNAMO_TABLE_NAME', apiKeysTable.tableName)
lambdaFunction.addEnvironment('DYNAMO_ANALYSIS_TABLE_NAME', analysisTable.tableName)

// ─── Export table names to amplify_outputs.json ───────────────────────────────
// The Nuxt app reads these automatically – no manual env-var setup required.

backend.addOutput({
  custom: {
    dynamoTableName: apiKeysTable.tableName,
    dynamoAnalysisTableName: analysisTable.tableName,
  },
})

// ─── IAM: grant apiFunction Lambda access to Amazon Comprehend and Bedrock ───

lambdaRole.addToPrincipalPolicy(
  new PolicyStatement({
    effect: Effect.ALLOW,
    actions: [
      'comprehend:DetectSentiment',
      'comprehend:DetectToxicContent',
    ],
    resources: ['*'],
  }),
)

lambdaRole.addToPrincipalPolicy(
  new PolicyStatement({
    effect: Effect.ALLOW,
    actions: [
      'bedrock:InvokeModel',
    ],
    resources: ['*'],
  }),
)
